#!/usr/bin/env python3
"""Run VideoSeek through non-invasive runtime hooks and emit trace v0.1 JSONL.

The wrapper deliberately imports a fixed VideoSeek checkout at runtime and never
edits it. API credentials are read only from a named environment variable and
are excluded from all manifests, trace events, arguments, and logs generated by
this wrapper.
"""

from __future__ import annotations

import argparse
import contextlib
import contextvars
import dataclasses
import datetime as datetime_module
import functools
import hashlib
import json
import os
import platform
import re
import resource
import subprocess
import sys
import time
import traceback
from pathlib import Path
from typing import Any, Callable, Iterable, Optional


SCHEMA_VERSION = "0.1"
_STEP_PATTERN = re.compile(r"Step \[(\d+) / \d+\]")


def _utc_now() -> str:
    return datetime_module.datetime.now(datetime_module.timezone.utc).isoformat().replace(
        "+00:00", "Z"
    )


def _round_ms(seconds: float) -> float:
    return round(seconds * 1000.0, 3)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as input_file:
        for chunk in iter(lambda: input_file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _command_output(command: list[str], *, timeout: float = 5.0) -> Optional[str]:
    try:
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return None
    if completed.returncode != 0:
        return None
    return completed.stdout.strip()


def _git_provenance(repository_root: Path) -> dict[str, Any]:
    commit = _command_output(["git", "-C", str(repository_root), "rev-parse", "HEAD"])
    if commit is None:
        return {"commit": None, "working_tree_clean": None}
    status = _command_output(
        ["git", "-C", str(repository_root), "status", "--porcelain"],
    )
    return {
        "commit": commit,
        "working_tree_clean": status == "" if status is not None else None,
    }


def _video_metadata(video_path: Path) -> dict[str, Any]:
    """Collect reproducible input facts without retaining video content."""
    metadata: dict[str, Any] = {
        "path": str(video_path),
        "size_bytes": video_path.stat().st_size,
        "sha256": _sha256(video_path),
        "duration_seconds": None,
        "video_codec": None,
        "resolution": None,
        "frame_rate": None,
    }
    output = _command_output(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration,format_name:stream=codec_type,codec_name,width,height,r_frame_rate",
            "-of",
            "json",
            str(video_path),
        ]
    )
    if output is None:
        return metadata
    try:
        probe = json.loads(output)
        if not isinstance(probe, dict):
            return metadata
        format_data = probe.get("format", {})
        streams = probe.get("streams", [])
        if not isinstance(format_data, dict):
            format_data = {}
        if not isinstance(streams, list):
            streams = []
        video_stream = next(
            (
                stream
                for stream in streams
                if isinstance(stream, dict) and stream.get("codec_type") == "video"
            ),
            {},
        )
        duration = format_data.get("duration")
        if duration is not None:
            metadata["duration_seconds"] = float(duration)
        codec = video_stream.get("codec_name")
        if isinstance(codec, str):
            metadata["video_codec"] = codec
        width, height = video_stream.get("width"), video_stream.get("height")
        if isinstance(width, int) and isinstance(height, int):
            metadata["resolution"] = [width, height]
        frame_rate = video_stream.get("r_frame_rate")
        if isinstance(frame_rate, str):
            metadata["frame_rate"] = frame_rate
    except (AttributeError, TypeError, ValueError, json.JSONDecodeError):
        pass
    return metadata


def _environment_metadata() -> dict[str, Any]:
    gpu = _gpu_snapshot()
    nvidia_smi = _command_output(["nvidia-smi"])
    cuda_version = None
    if nvidia_smi is not None:
        matched = re.search(r"CUDA Version:\s*([0-9.]+)", nvidia_smi)
        if matched:
            cuda_version = matched.group(1)
    return {
        "python_version": platform.python_version(),
        "python_implementation": platform.python_implementation(),
        "cuda_version": cuda_version,
        "gpu": gpu or None,
    }


def _json_safe(value: Any, *, max_text: int = 2000) -> Any:
    """Return a bounded JSON-compatible representation without serializing media."""
    if value is None or isinstance(value, (bool, int, float)):
        return value
    if isinstance(value, str):
        return value[:max_text]
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(key): _json_safe(item, max_text=max_text) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item, max_text=max_text) for item in value]
    return str(value)[:max_text]


def _process_peak_rss_mb() -> Optional[float]:
    try:
        raw = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    except (AttributeError, OSError):
        return None
    divisor = 1024.0 * 1024.0 if sys.platform == "darwin" else 1024.0
    return round(raw / divisor, 3)


def _gpu_snapshot() -> dict[str, Any]:
    """Sample system-level GPU state without adding a Python dependency."""
    command = [
        "nvidia-smi",
        "--query-gpu=index,name,driver_version,memory.used,memory.total,utilization.gpu",
        "--format=csv,noheader,nounits",
    ]
    try:
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return {}
    if completed.returncode != 0 or not completed.stdout.strip():
        return {}
    fields = [field.strip() for field in completed.stdout.splitlines()[0].split(",")]
    if len(fields) != 6:
        return {}
    try:
        return {
            "system_gpu_index": int(fields[0]),
            "gpu_model": fields[1],
            "gpu_driver_version": fields[2],
            "system_gpu_memory_used_mib": float(fields[3]),
            "system_gpu_memory_total_mib": float(fields[4]),
            "system_gpu_utilization_pct": float(fields[5]),
        }
    except ValueError:
        return {"gpu_model": fields[1]}


@dataclasses.dataclass
class _ActiveAction:
    step_id: int
    action: str
    api_wait_ms: float = 0.0
    api_call_count: int = 0


class TraceRecorder:
    """Append schema-v0.1 events while retaining no secrets or media payloads."""

    def __init__(
        self,
        run_dir: Path,
        *,
        run_id: str,
        framework: str,
        dataset: str,
        task_id: str,
        model_id: str,
    ) -> None:
        self.run_dir = run_dir
        self.run_id = run_id
        self.framework = framework
        self.dataset = dataset
        self.task_id = task_id
        self.model_id = model_id
        self.trace_path = run_dir / "trace.jsonl"
        self._trace_file = self.trace_path.open("w", encoding="utf-8")
        self._event_count = 0
        self._error_event_count = 0
        self._retry_event_count = 0
        self._planning_step = 0
        self._active_action: contextvars.ContextVar[Optional[_ActiveAction]] = (
            contextvars.ContextVar("videoseek_active_action", default=None)
        )

    @property
    def planning_step(self) -> int:
        return self._planning_step

    @property
    def event_count(self) -> int:
        return self._event_count

    @property
    def error_event_count(self) -> int:
        return self._error_event_count

    @property
    def retry_event_count(self) -> int:
        return self._retry_event_count

    def close(self) -> None:
        self._trace_file.close()

    def infer_step_id(self, messages: Any) -> int:
        if isinstance(messages, list):
            for message in reversed(messages):
                if not isinstance(message, dict):
                    continue
                content = message.get("content")
                if not isinstance(content, str):
                    continue
                matched = _STEP_PATTERN.search(content)
                if matched:
                    self._planning_step = int(matched.group(1))
                    return self._planning_step
        self._planning_step = max(1, self._planning_step)
        return self._planning_step

    @contextlib.contextmanager
    def action_context(self, step_id: int, action: str) -> Iterable[_ActiveAction]:
        active = _ActiveAction(step_id=step_id, action=action)
        token = self._active_action.set(active)
        try:
            yield active
        finally:
            self._active_action.reset(token)

    def _resource(
        self,
        runtime_ms: float,
        api_wait_ms: float,
        resource_overrides: Optional[dict[str, Any]] = None,
    ) -> dict[str, Any]:
        gpu = _gpu_snapshot()
        local_runtime_ms = max(0.0, _round_ms((runtime_ms - api_wait_ms) / 1000.0))
        resource = {
            "gpu_id": gpu.get("system_gpu_index"),
            "gpu_model": gpu.get("gpu_model"),
            "queue_ms": None,
            "decode_ms": None,
            "load_ms": None,
            "runtime_ms": runtime_ms,
            "api_wait_ms": api_wait_ms,
            "local_runtime_ms": local_runtime_ms,
            "peak_allocated_mb": None,
            "peak_reserved_mb": None,
            "process_max_rss_mb": _process_peak_rss_mb(),
            **gpu,
        }
        if resource_overrides:
            # Adapters may provide measured decode/load timings while the
            # recorder still owns the common GPU and runtime fields.
            resource.update(_json_safe(resource_overrides))
        return resource

    def record_event(
        self,
        *,
        event_type: str,
        step_id: int,
        action: str,
        node_type: str,
        parent_step_ids: list[int],
        input_data: dict[str, Any],
        start_time: str,
        end_time: str,
        runtime_ms: float,
        api_wait_ms: float,
        status: str,
        output_summary_ref: Optional[str],
        model_id: Optional[str] = None,
        retry_of: Optional[str] = None,
        error: Optional[str] = None,
        resource_overrides: Optional[dict[str, Any]] = None,
    ) -> None:
        self._event_count += 1
        event_id = f"{self.run_id}:{event_type}:{self._event_count}"
        if status == "error":
            self._error_event_count += 1
        if retry_of is not None:
            self._retry_event_count += 1
        event = {
            "schema_version": SCHEMA_VERSION,
            "event_id": event_id,
            "event_type": event_type,
            "run_id": self.run_id,
            "framework": self.framework,
            "dataset": self.dataset,
            "task_id": self.task_id,
            "step_id": step_id,
            "parent_step_ids": parent_step_ids,
            "action": action,
            "node_type": node_type,
            "model_id": model_id or self.model_id,
            "model_resident_before": None,
            "input": _json_safe(input_data),
            "resource": self._resource(runtime_ms, api_wait_ms, resource_overrides),
            "status": status,
            "retry_of": retry_of,
            "output_summary_ref": output_summary_ref,
            "timestamp_start": start_time,
            "timestamp_end": end_time,
            "error": error,
        }
        json.dump(event, self._trace_file, ensure_ascii=False, sort_keys=True)
        self._trace_file.write("\n")
        self._trace_file.flush()

    def wrap_llm_call(self, original: Callable[..., Any], module_name: str) -> Callable[..., Any]:
        """Capture remote API wait without storing request content or credentials."""

        @functools.wraps(original)
        def wrapped(*args: Any, **kwargs: Any) -> Any:
            start_wall = _utc_now()
            start_perf = time.perf_counter()
            active = self._active_action.get()
            messages = kwargs.get("messages")
            if active is None:
                step_id = self.infer_step_id(messages)
                action = "llm_plan"
                parent_step_ids = [step_id - 1] if step_id > 1 else []
                input_data = {"module": module_name, "request_kind": "planning"}
            else:
                step_id = active.step_id
                action = f"{active.action}.llm_api"
                parent_step_ids = [step_id]
                input_data = {
                    "module": module_name,
                    "request_kind": "tool_or_answer",
                    "parent_action": active.action,
                }
            status = "success"
            error = None
            try:
                result = original(*args, **kwargs)
                if result is None:
                    status = "error"
                    error = "VideoSeek call_llm_api returned None"
                return result
            except BaseException as exc:
                status = "error"
                error = f"{type(exc).__name__}: {exc}"
                raise
            finally:
                elapsed_ms = _round_ms(time.perf_counter() - start_perf)
                if active is not None:
                    active.api_wait_ms += elapsed_ms
                    active.api_call_count += 1
                self.record_event(
                    event_type="api_call",
                    step_id=step_id,
                    action=action,
                    node_type="remote_llm_api",
                    parent_step_ids=parent_step_ids,
                    input_data=input_data,
                    start_time=start_wall,
                    end_time=_utc_now(),
                    runtime_ms=elapsed_ms,
                    api_wait_ms=elapsed_ms,
                    status=status,
                    output_summary_ref=f"trace.jsonl:api-{self._event_count + 1}",
                    error=error,
                )

        return wrapped


def _tool_node_type(action: str) -> str:
    if action in {"overview", "skim", "focus"}:
        return "video_observation"
    if action == "answer":
        return "answer_generation"
    return "agent_action"


def _install_llm_hooks(recorder: TraceRecorder) -> Callable[[], None]:
    """Patch only imported module aliases, and return an idempotent restore function."""
    import videoseek.agent as agent_module
    import videoseek.tools.answer as answer_module
    import videoseek.tools.focus as focus_module
    import videoseek.tools.overview as overview_module
    import videoseek.tools.skim as skim_module

    patched: list[tuple[Any, Callable[..., Any]]] = []
    for module in (agent_module, answer_module, focus_module, overview_module, skim_module):
        original = getattr(module, "call_llm_api", None)
        if not callable(original):
            continue
        setattr(module, "call_llm_api", recorder.wrap_llm_call(original, module.__name__))
        patched.append((module, original))

    def restore() -> None:
        for module, original in reversed(patched):
            setattr(module, "call_llm_api", original)

    return restore


def _install_action_hook(agent: Any, recorder: TraceRecorder, video_path: str) -> Callable[[], None]:
    attribute = "_VideoSeekAgent__exec_action"
    original = getattr(agent, attribute)

    @functools.wraps(original)
    def wrapped(action_object: Any) -> Any:
        action_name = str(getattr(action_object, "function_name", "unknown"))
        step_id = recorder.planning_step or (len(agent.trajectory_steps) + 1)
        parameters = _json_safe(getattr(action_object, "parameters", {}) or {})
        start_wall = _utc_now()
        start_perf = time.perf_counter()
        status = "success"
        error = None
        active: Optional[_ActiveAction] = None
        try:
            with recorder.action_context(step_id, action_name) as active:
                result = original(action_object)
            if result == "Tool execution failed.":
                status = "error"
                error = "VideoSeek tool returned its failure sentinel"
            return result
        except BaseException as exc:
            status = "error"
            error = f"{type(exc).__name__}: {exc}"
            raise
        finally:
            api_wait_ms = active.api_wait_ms if active is not None else 0.0
            api_call_count = active.api_call_count if active is not None else 0
            elapsed_ms = _round_ms(time.perf_counter() - start_perf)
            recorder.record_event(
                event_type="action",
                step_id=step_id,
                action=action_name,
                node_type=_tool_node_type(action_name),
                parent_step_ids=[step_id - 1] if step_id > 1 else [],
                input_data={
                    "video_path": video_path,
                    "parameters": parameters,
                    "nested_api_call_count": api_call_count,
                },
                start_time=start_wall,
                end_time=_utc_now(),
                runtime_ms=elapsed_ms,
                api_wait_ms=round(api_wait_ms, 3),
                status=status,
                output_summary_ref=f"trace.jsonl:action-{recorder._event_count + 1}",
                error=error,
            )

    setattr(agent, attribute, wrapped)

    def restore() -> None:
        setattr(agent, attribute, original)

    return restore


class _Tee:
    def __init__(self, *streams: Any) -> None:
        self._streams = streams

    def write(self, text: str) -> int:
        for stream in self._streams:
            stream.write(text)
            stream.flush()
        return len(text)

    def flush(self) -> None:
        for stream in self._streams:
            stream.flush()


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--videoseek-root", required=True, type=Path)
    parser.add_argument("--video-path", required=True, type=Path)
    parser.add_argument("--user-query", required=True)
    parser.add_argument("--output-root", required=True, type=Path)
    parser.add_argument("--dataset", default="lvbench")
    parser.add_argument("--task-id", default=None)
    parser.add_argument("--model-name", default="openai/qwen3-vl-plus")
    parser.add_argument("--api-base-env", default="OPENAI_API_BASE")
    parser.add_argument("--api-key-env", default="OPENAI_API_KEY")
    parser.add_argument("--api-version-env", default="OPENAI_API_VERSION")
    parser.add_argument("--max-steps", type=int, default=20)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--max-tokens", type=int, default=32768)
    parser.add_argument("--reasoning-effort", default="medium")
    return parser


def _run(args: argparse.Namespace) -> int:
    videoseek_root = args.videoseek_root.expanduser().resolve()
    video_path = args.video_path.expanduser().resolve()
    if not (videoseek_root / "videoseek" / "agent.py").is_file():
        raise FileNotFoundError(f"Not a VideoSeek checkout: {videoseek_root}")
    if not video_path.is_file():
        raise FileNotFoundError(f"Video does not exist: {video_path}")
    api_base = os.getenv(args.api_base_env)
    api_key = os.getenv(args.api_key_env)
    if not api_base:
        raise RuntimeError(f"Required API base environment variable is unset: {args.api_base_env}")
    if not api_key:
        raise RuntimeError(f"Required API key environment variable is unset: {args.api_key_env}")

    run_id = f"{video_path.stem}_{int(time.time())}"
    run_dir = args.output_root.expanduser().resolve() / run_id
    run_dir.mkdir(parents=True, exist_ok=False)
    task_id = args.task_id or video_path.stem
    run_started_at = _utc_now()
    start_perf = time.perf_counter()
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "run_id": run_id,
        "framework": "videoseek",
        "dataset": args.dataset,
        "task_id": task_id,
        "video_path": str(video_path),
        "videoseek_root": str(videoseek_root),
        "model_name": args.model_name,
        "api_base_env": args.api_base_env,
        "api_key_env": args.api_key_env,
        "api_version_env": args.api_version_env,
        "max_steps": args.max_steps,
        "seed": args.seed,
        "temperature": args.temperature,
        "max_tokens": args.max_tokens,
        "reasoning_effort": args.reasoning_effort,
        "task_query_sha256": hashlib.sha256(args.user_query.encode("utf-8")).hexdigest(),
        "input_metadata": _video_metadata(video_path),
        "source_provenance": _git_provenance(videoseek_root),
        "environment": _environment_metadata(),
        "external_api": {
            "enabled": True,
            "api_base_env": args.api_base_env,
            "api_key_env": args.api_key_env,
            "api_version_env": args.api_version_env,
        },
        "started_at": run_started_at,
        "status": "running",
    }
    manifest_path = run_dir / "run_manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    recorder = TraceRecorder(
        run_dir,
        run_id=run_id,
        framework="videoseek",
        dataset=args.dataset,
        task_id=task_id,
        model_id=args.model_name,
    )
    exit_code = 1
    error = None
    prediction = ""
    restore_hooks: list[Callable[[], None]] = []
    log_path = run_dir / "stdout_stderr.log"
    try:
        sys.path.insert(0, str(videoseek_root))
        from config import general_config, prompts_config  # type: ignore
        from videoseek.agent import VideoSeekAgent  # type: ignore

        config = {**general_config, **prompts_config}
        config.update(
            {
                "model_name": args.model_name,
                "api_base": api_base,
                "api_key": api_key,
                "api_version": os.getenv(args.api_version_env),
                "max_steps": args.max_steps,
                "seed": args.seed,
                "temperature": args.temperature,
                "max_tokens": args.max_tokens,
                "reasoning_effort": args.reasoning_effort,
            }
        )
        with log_path.open("w", encoding="utf-8") as log_file:
            tee = _Tee(sys.stdout, log_file)
            with contextlib.redirect_stdout(tee), contextlib.redirect_stderr(tee):
                agent = VideoSeekAgent(
                    config=config,
                    video_path=str(video_path),
                    subtitle_path=None,
                    output_dir=str(run_dir),
                    tools=config["tools"],
                    verbose=True,
                )
                restore_hooks.append(_install_llm_hooks(recorder))
                restore_hooks.append(_install_action_hook(agent, recorder, str(video_path)))
                trajectory = agent.run(args.user_query)
                trajectory_dict = trajectory.to_dict()
                prediction = trajectory_dict.get("final_answer", "")
                (run_dir / "prediction.json").write_text(
                    json.dumps({"prediction": prediction}, ensure_ascii=False, indent=2) + "\n",
                    encoding="utf-8",
                )
                (run_dir / "trajectory.json").write_text(
                    json.dumps(trajectory_dict, ensure_ascii=False, indent=2) + "\n",
                    encoding="utf-8",
                )
                print(f"Prediction: {prediction}")
        exit_code = 0
    except BaseException as exc:
        error = f"{type(exc).__name__}: {exc}"
        with log_path.open("a", encoding="utf-8") as log_file:
            traceback.print_exc(file=log_file)
        print(error, file=sys.stderr)
    finally:
        for restore in reversed(restore_hooks):
            restore()
        elapsed_seconds = round(time.perf_counter() - start_perf, 3)
        recorder.record_event(
            event_type="run",
            step_id=0,
            action="run",
            node_type="agent_run",
            parent_step_ids=[],
            input_data={
                "video_path": str(video_path),
                "contains_external_api": True,
            },
            start_time=run_started_at,
            end_time=_utc_now(),
            runtime_ms=_round_ms(elapsed_seconds),
            api_wait_ms=0.0,
            status="success" if exit_code == 0 else "error",
            output_summary_ref="run_manifest.json",
            error=error,
        )
        manifest.update(
            {
                "finished_at": _utc_now(),
                "status": "success" if exit_code == 0 else "error",
                "exit_code": exit_code,
                "elapsed_seconds": elapsed_seconds,
                "error": error,
                "trace_path": str(recorder.trace_path),
                "outcome": {
                    "prediction": _json_safe(prediction, max_text=1000),
                    "trace_event_count": recorder.event_count,
                    "error_event_count": recorder.error_event_count,
                    "retry_event_count": recorder.retry_event_count,
                },
            }
        )
        manifest_path.write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        (run_dir / "run_status.json").write_text(
            json.dumps(
                {
                    "exit_code": exit_code,
                    "elapsed_seconds": elapsed_seconds,
                    "error": error,
                    "trace_event_count": recorder.event_count,
                    "error_event_count": recorder.error_event_count,
                    "retry_event_count": recorder.retry_event_count,
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        recorder.close()
    print(run_dir)
    return exit_code


def main(argv: Optional[list[str]] = None) -> int:
    return _run(_build_parser().parse_args(argv))


if __name__ == "__main__":
    raise SystemExit(main())
